kiva/protocol-common

- .npmrc
- package-lock.json
- package.json
- publish.sh
PRO-2111
Changes are for making the package available on the standard npm repo
We might have to remove automatic deployment of packages from CI/CD
> Updates for making package available publicly

- package-lock.json
- package.json
- src/protocol.utility.ts
PRO-2325
We use an anonymous method to compute delta in two Date types in a lot of places.  Moving it protocol common
> adds new time diff function

- .circleci/config.yml
PRO-2333
Adds linter calls to build process steps
> adds linter to build and test

- src/datadog.logger.ts
|       |       |   @voutasaurus    |       |       |
PRO 2402
Makes sure we log json in QA, and for any new envs we add 
FYI @matt-raffel-kiva if you're upping the version soon we can just include this change in there
> Log json in QA and by default

- package.json
- src/protocol.utility.ts
- test/package.e2e-spec.ts
PRO-2332
Adds new static method that contains the common loop logic of retrying until success or timeout.
> Adds logic for handling retries

- .npmrc
- package.json
- publish.sh
Signed-off-by: Anthony Voutas <anthonyv@kiva.org>
The automated deploy is failing due to auth issue.
Add authentication mechanism
> set up npm registry auth and force update

- .circleci/config.yml
- publish.sh
Signed-off-by: Anthony Voutas <anthonyv@kiva.org>
npm publish gives 404, cause is unclear
increase logging level to debug issue
> cicd: debug logging

- package.json
Signed-off-by: Anthony Voutas <anthonyv@kiva.org>
interactions with registry are currently unencrypted
use https
> encrypt registry interactions

- .circleci/config.yml
- package-lock.json
- package.json
- tsconfig.json
> update circle ci

- package-lock.json
- package.json
- src/tracer.ts
> security fix

- package-lock.json
- package.json
- src/protocol.http.service.ts
> fix logger

- package.json
- src/logger.ts
> PRO-2535 adding method for debug logging

- package-lock.json
- package.json
- src/protocol.errorcode.ts
> add new error codes

- package-lock.json
- package.json
- src/protocol.errorcode.ts
- src/protocol.exception.filter.ts
> hack around instance of failures

- .circleci/config.yml
- PULL_REQUEST_TEMPLATE.md
- README.md
- package-lock.json
- package.json
> update master references to main

- package.json
- src/validation/common/builders/is.number.builder.ts
- src/validation/common/builders/is.string.builder.ts
- src/validation/decorators/parameter/is.number.decorator.ts
- src/validation/decorators/parameter/is.string.decorator.ts
- src/validation/validations/is.number.ts
- src/validation/validations/is.string.ts
- test/validation/decorators/parameter/is.number.decorator.spec.ts
- test/validation/decorators/parameter/is.string.decorator.spec.ts
- test/validation/validations/is.integer.spec.ts
- test/validation/validations/is.number.spec.ts
- test/validation/validations/is.string.spec.ts
*([Click here](https://github.com/kiva/protocol/blob/main/PULL_REQUEST_README.md) if you don't understand these emojis)*
> PRO-3166: Add IsNumber and IsString validations

- package-lock.json
- package.json
- src/date.conversion.ts
- src/protocol.errorcode.ts
- test/date.conversion-spec.ts
*([Click here](https://github.com/kiva/protocol/blob/main/PULL_REQUEST_README.md) if you don't understand these emojis)*
Submitted an RFC for representing dates in credentials here: https://github.com/hyperledger/aries-rfcs/pull/687
This PR adds some convenience functions for translating to and from this dateint format.
> add date conversion class

- package-lock.json
- package.json
- src/date.conversion.ts
*([Click here](https://github.com/kiva/protocol/blob/main/PULL_REQUEST_README.md) if you don't understand these emojis)*
> fix import issue on date conversion

- package-lock.json
- package.json
- src/random.string.generator.ts
*([Click here](https://github.com/kiva/protocol/blob/main/PULL_REQUEST_README.md) if you don't understand these emojis)*
Last one I promise :) 
> one more fix

- docs/migrate.to.v1.md
> Updating migration doc
